pref("extensions.paperAcquisitionAntiScrape.serviceURL", "http://127.0.0.1:24372");
pref("extensions.paperAcquisitionAntiScrape.autoStartService", true);
pref("extensions.paperAcquisitionAntiScrape.serviceWorkingDirectory", "");
pref("extensions.paperAcquisitionAntiScrape.serviceStartCommand", "npm start");
pref("extensions.paperAcquisitionAntiScrape.defaultProfile", "auto");
pref("extensions.paperAcquisitionAntiScrape.browserEngine", "chrome-first");
pref("extensions.paperAcquisitionAntiScrape.cookieSyncDomains", "");
pref("extensions.paperAcquisitionAntiScrape.proxyMode", "profile");
pref("extensions.paperAcquisitionAntiScrape.proxyServer", "");
pref("extensions.paperAcquisitionAntiScrape.proxyUsername", "");
pref("extensions.paperAcquisitionAntiScrape.proxyPassword", "");
pref("extensions.paperAcquisitionAntiScrape.skipExistingPDF", true);
pref("extensions.paperAcquisitionAntiScrape.showProgressWindow", true);
pref("extensions.paperAcquisitionAntiScrape.autoAcquireOnNewItems", false);
pref("extensions.paperAcquisitionAntiScrape.autoAcquireDelayMS", 30000);
pref("extensions.paperAcquisitionAntiScrape.avoidNativeDownloadConflicts", true);
pref("extensions.paperAcquisitionAntiScrape.pollIntervalMS", 1500);
pref("extensions.paperAcquisitionAntiScrape.jobTimeoutMS", 600000);
